url: "https://matthieuporte.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "matthiru" # the name of your site, e.g. ACME Corp.

collections:
  projects:
    output: true